### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by fredmaiaarantes**
Create pt-br.json to start the Brazilian Portuguese translation.

### CODE REVIEW

**Comment by JuanM04** [comment]
Thank you for contributing to Blitz! We will wait a bit until you have another maintainer to help you. If you know anyone interested, you could add them

**Comment by fmilani** [comment]
I can help!

**Comment by fredmaiaarantes** [comment]
> Thank you for contributing to Blitz! We will wait a bit until you have another maintainer to help you. If you know anyone interested, you could add them

Hey @JuanM04, I think we can start working on it. :)

**Comment by JuanM04** [comment]
Amazing, thank you both!

**Comment by buzs** [comment]
I would like to help

**Comment by fredmaiaarantes** [comment]
That's great @buzs! Just follow the process from here: https://github.com/blitz-js/pt-br.blitzjs.com/issues/1

I'll start it today and just claimed the home page. :)

**Pull request merged**
