### PR TITLE
Simplified Chinese maintainers

### PR DESCRIPTION
**Pull request by linbudu599**
Chinese Translation Preparation.

### CODE REVIEW

**Comment by JuanM04** [comment]
Which script will you translate to? Simplified Chinese or Traditional Chinese?

**Comment by linbudu599** [comment]
> Which script will you translate to? Simplified Chinese or Traditional Chinese?

Simplified Chinese, should I update name to 'Simplified Chinese'? `Traditional Chinese` shares language code 'zh' with `Simplified Chinese`.

**Comment by JuanM04** [comment]
Yeah, I think we should use `zh-hans`, but we aren't sure. There's a issue about this: #6

We'll decide once you get another maintainer to help

**Comment by flybayer** [comment]
I agree, let's follow same as reactjs.com

**Comment by JuanM04** [comment]
@linbudu599 You will be the only maintainer (for now). You won't have branch protection, so you can start doing the translations.

Thanks for helping!

**Pull request merged**
