### PR TITLE
Adding french translation

### PR DESCRIPTION
**Pull request by Mangiang**
Bonjour !
Je souhaite commencer la traduction française. Si vous êtes intéressé, n'hésitez pas à me rejoindre !

Hello !
If anyone is interested in helping me maintain the french translation, feel free to join me !

### CODE REVIEW

**Comment by JuanM04** [comment]
Thank you for your willingness to contribute to Blitz. We will wait a bit until you have another maintainer to help you :smile:

**Comment by emeraldsanto** [comment]
I actually put my name down for french in another issue a very long time ago, still up for it!

**Comment by SaloniThete** [comment]
I would like to help @Mangiang in maintaining french translation.

**Comment by Mangiang** [comment]
The more, the merrier ?

**Comment by SaloniThete** [comment]
yes of course :)

**Comment by JuanM04** [comment]
Perfect! So, @emeraldsanto @SaloniThete, both of you want to be maintainers, or just help out?

**Comment by louishugens** [comment]
I can help too

**Comment by JuanM04** [comment]
Thank you everyone to be so interested in the French translation :heart:
If you want to be a [maintainer](https://github.com/blitz-js/blitzjs.com-translation/blob/main/docs/maintainer-guide.md), please react to this comment with the Rocket (:rocket:), so I include you in the maintainer list. Otherwise, if you just want to help out, subscribe to this PR to get notified when the repo gets created

**Comment by SaloniThete** [comment]
Thank you @JuanM04, I would have liked to be a maintainer but my plate is full at the moment.so I would love to contribute to the repo and have subscribed too.

**Comment by JuanM04** [comment]
Hey, everyone, the repo was created here: https://github.com/blitz-js/fr.blitzjs.com/issues/1
You all can start translating and reviewing, and the maintainers also may assign pages so one page is translated by one person.

Also, I created the channel `#lang-french` in the [Blitz.js Discord Server](https://blitzjs.com/discord) for you to communicate :smile:

**Comment by Mangiang** [comment]
Thank you @JuanM04  !

If anyone needs to ping me, my ID is `Shirito#4361` in Discord

**Pull request merged**
