### PR TITLE
Add Indonesian Language

### PR DESCRIPTION
**Pull request by ghost**
Hi, I want to add Indonesian language, @indiealistic and @racheloveyou is Indonesian native speaker

Thanks :)

### CODE REVIEW

**Comment by ghost** [comment]
I'm ready to help

**Comment by flybayer** [comment]
Yay! This is so exciting :D

**Comment by flybayer** [comment]
I've added a `#lang-indonesian` channel in discord for y'all

**Comment by ghost** [comment]
> I've added a `#lang-indonesian` channel in discord for y'all

Awesome i'll invite other indonesian to

**Comment by JuanM04** [comment]
> Awesome i'll invite other indonesian to

Perfect. We'll leave this PR open a few more time so your friend (or anyone) joins

**Review by JuanM04 — APPROVED** [review]

**Pull request merged**
