### PR TITLE
Create it.json

### PR DESCRIPTION
**Pull request by mlabate**

### CODE REVIEW

**Comment by JuanM04** [comment]
Thank you for contributing to Blitz! Before creating the `it.blitzjs.com` repo, we will wait a bit until you have another maintainer to help you. If you know anyone interested, you could add they

**Comment by mlabate** [comment]
Hello Juan, great, I'll be wait for any news and I'm going to look for someone, too :)
Thank you.

**Comment by Dieman89** [comment]
Here I am :)

**Comment by JuanM04** [comment]
@Dieman89 Thank you!

**Pull request merged**
